return {
	--	"neovim/nvim-lspconfig",
	--	dependencies = {
	--		"folke/lazydev.nvim",
	--		ft = "lua",
	--		opts = {
	--			library = {
	--				{ path = "${3rd}/luv/library", words = { "vim%.uv" } },
	--			},
	--			servers = {
	--				bacon_ls = {
	--					enabled = diagnostics == "bacon-ls",
	--				},
	--				rust_analyzer = { enabled = false },
	--			},
	--		},
	--	},
	--	config = function()
	--		-- Configure error/warnings interface
	--		vim.diagnostic.config({
	--			virtual_text = true,
	--			severity_sort = true,
	--			float = {
	--				style = 'minimal',
	--				border = 'rounded',
	--				header = '',
	--				prefix = '',
	--			},
	--			signs = {
	--				text = {
	--					[vim.diagnostic.severity.ERROR] = '✘',
	--					[vim.diagnostic.severity.WARN] = '▲',
	--					[vim.diagnostic.severity.HINT] = '⚑',
	--					[vim.diagnostic.severity.INFO] = '»',
	--				},
	--			},
	--		})
	--
	--		-- put early in lsp.lua
	--		local orig = vim.lsp.util.open_floating_preview
	--		---@diagnostic disable-next-line: duplicate-set-field
	--		function vim.lsp.util.open_floating_preview(contents, syntax, opts, ...)
	--			opts            = opts or {}
	--			opts.border     = opts.border or 'rounded'
	--			opts.max_width  = opts.max_width or 80
	--			opts.max_height = opts.max_height or 24
	--			opts.wrap       = opts.wrap ~= false
	--			return orig(contents, syntax, opts, ...)
	--		end
	--
	--		-- Per-buffer behavior on LSP attach (keymaps, auto-format, completion)
	--		-- See :help LspAttach for the recommended pattern
	--		vim.api.nvim_create_autocmd('LspAttach', {
	--			group = vim.api.nvim_create_augroup('my.lsp', {}),
	--			callback = function(args)
	--				local client = assert(vim.lsp.get_client_by_id(args.data.client_id))
	--				local buf    = args.buf
	--				local map    = function(mode, lhs, rhs) vim.keymap.set(mode, lhs, rhs, { buffer = buf }) end
	--
	--				-- Keymaps (use builtin LSP buffer functions)
	--				map('n', 'K', vim.lsp.buf.hover)
	--				map('n', 'gd', vim.lsp.buf.definition)
	--				map('n', 'gD', vim.lsp.buf.declaration)
	--				map('n', 'gi', vim.lsp.buf.implementation)
	--				map('n', 'go', vim.lsp.buf.type_definition)
	--				map('n', 'gr', vim.lsp.buf.references)
	--				map('n', 'gs', vim.lsp.buf.signature_help)
	--				map('n', 'gl', vim.diagnostic.open_float)
	--				map('n', '<F2>', vim.lsp.buf.rename)
	--				map({ 'n', 'x' }, '<F3>', function() vim.lsp.buf.format({ async = true }) end)
	--				map('n', '<F4>', vim.lsp.buf.code_action)
	--
	--				-- Put near your LSP on_attach
	--				local excluded_filetypes = { php = true }
	--
	--				-- Auto-format on save (only if server can't do WillSaveWaitUntil)
	--				if not client:supports_method('textDocument/willSaveWaitUntil')
	--					and client:supports_method('textDocument/formatting')
	--					and not excluded_filetypes[vim.bo[buf].filetype]
	--				then
	--					vim.api.nvim_create_autocmd('BufWritePre', {
	--						group = vim.api.nvim_create_augroup('my.lsp.format', { clear = false }),
	--						buffer = buf,
	--						callback = function()
	--							vim.lsp.buf.format({ bufnr = buf, id = client.id, timeout_ms = 1000 })
	--						end,
	--					})
	--				end
	--			end,
	--		})
	--
	--		-- 				LSP SERVERS
	--		--	Lua
	--		require("lspconfig").lua_ls.setup {}
	--
	--		-- C/C++
	--		vim.lsp.config['clangd'] = {
	--			cmd = {
	--				'clangd',
	--				'--clang-tidy',
	--				'--background-index',
	--				'--offset-encoding=utf-8',
	--			},
	--			root_markers = { 'clangd', 'compile_commands.json' },
	--			filetypes = { 'c', 'cpp', 'c', 'h', 'hpp' }
	--		}
	--
	--
	--		-- Python
	--		require("lspconfig").pylsp.setup {
	--			on_attach = function(client, bufnr)
	--				-- Optional: Set up key mappings
	--				local opts = { buffer = bufnr }
	--				vim.keymap.set("n", "gd", vim.lsp.buf.declaration, opts)
	--				vim.keymap.set("n", "gD", vim.lsp.buf.implementation, opts)
	--				vim.keymap.set("n", "K", vim.lsp.buf.hover, opts)
	--				vim.keymap.set("n", "gi", vim.lsp.buf.type_definition, opts)
	--				vim.keymap.set("n", "gr", vim.lsp.buf.references, opts)
	--				vim.keymap.set("n", "<C-]>", vim.lsp.buf.definition, opts)
	--				vim.keymap.set("n", "<C-k>", vim.lsp.buf.signature_help, opts)
	--			end,
	--			settings = {
	--				pylsp = {
	--					plugins = {
	--						-- Enable specific plugins like linters, formatters, and type checkers
	--						black = { enabled = true },
	--						autopep8 = { enabled = false },
	--						yapf = { enabled = false },
	--						pylint = { enabled = true },
	--						pyflakes = { enabled = false },
	--						pycodestyle = { enabled = false },
	--						pylsp_mypy = { enabled = true },
	--						jedi_completion = { fuzzy = true },
	--						isort = { enabled = true },
	--					},
	--				},
	--			},
	--			flags = {
	--				debounce_text_changes = 200,
	--			},
	--		}
	--
	--		vim.lsp.enable('clangd')
	--	end,
}
